version: 2
updates:
- package-ecosystem: npm
  directory: "/website"
  schedule:
    interval: daily
    time: "13:00"
    timezone: Canada/Eastern
  open-pull-requests-limit: 2
  labels:
  - dependencies
  ignore:
  - dependency-name: bl
    versions:
    - 1.2.3
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: docusaurus
    versions:
    - 1.14.6
